# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-11 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MISS', 'Miss')], max_length=6, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('degree', models.CharField(blank=True, max_length=25, null=True)),
                ('speciality', models.CharField(blank=True, max_length=120, null=True)),
                ('house_number', models.CharField(blank=True, max_length=120, null=True)),
                ('street', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('pin', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MISS', 'Miss')], max_length=6, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('house_number', models.CharField(blank=True, max_length=120, null=True)),
                ('street', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('pin', models.PositiveIntegerField(blank=True, null=True)),
                ('time_admitted', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Doctor')),
            ],
            options={
                'ordering': ['-time_admitted'],
            },
            managers=[
                ('admitted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_discharged', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('medical_exp', models.DecimalField(decimal_places=2, default=9.99, max_digits=25)),
                ('rent', models.DecimalField(decimal_places=2, default=9.99, max_digits=25)),
                ('service_charges', models.DecimalField(decimal_places=2, default=9.99, max_digits=25)),
                ('subtotal', models.DecimalField(decimal_places=2, default=9.99, max_digits=25)),
                ('tax_total', models.DecimalField(decimal_places=2, default=9.99, max_digits=25)),
                ('total', models.DecimalField(decimal_places=2, default=9.99, max_digits=25)),
                ('auth_discharge', models.BooleanField(default=False)),
                ('auth_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='register.Doctor')),
                ('patient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='register.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent', models.IntegerField(default=1)),
                ('gm', models.IntegerField(default=1)),
                ('ortho', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Ward'),
        ),
    ]
