# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-11 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ward',
            old_name='ent',
            new_name='ward_no',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='gm',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='ortho',
        ),
    ]
