# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_ward_occupied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ward',
            old_name='ward_no',
            new_name='no_of_wards',
        ),
        migrations.AddField(
            model_name='ward',
            name='department',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
