# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20160612_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=20, null=True)),
                ('ward_no', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-time_discharged']},
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='occupied',
            new_name='is_occupied',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='no_of_wards',
        ),
        migrations.AlterField(
            model_name='payment',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=25),
        ),
        migrations.AlterField(
            model_name='ward',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Department'),
        ),
    ]
