# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20160613_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='ward_no',
        ),
        migrations.AddField(
            model_name='department',
            name='no_of_wards',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='ward',
            name='ward_no',
            field=models.IntegerField(default=1),
        ),
    ]
