# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20160613_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='department',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ward',
        ),
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Department'),
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
