# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-14 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20160614_0546'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='patient',
            managers=[
            ],
        ),
    ]
