# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-14 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20160614_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='auth_discharge',
            new_name='is_approved_discharge',
        ),
        migrations.AddField(
            model_name='patient',
            name='is_discharged',
            field=models.BooleanField(default=False),
        ),
    ]
